### ISSUE TITLE
Server Request

### ISSUE THREAD

**Issue by min-guk** [DKU-StarLab/leveldb-study#1]
Students who need a Linux server for study purposes, please write a comment below until Friday, July 8. 

You will receive a Linux server courtesy of DKU through Prof. Seehwan Yoo.

**Comment by seehwan** [comment]
Leave some message, as shown in the following example:
(index). (your name) (account_id) 
0.  seehwan.yoo seehwan14
The initial password will be set automatically. (I will let you know in the seminar session).
Preferred ID format is (yourname)+(2digits) e.g.) shyoo14 or seehwan14

We are going to use assam.dankook.ac.kr server so you can make an ssh connection through
your_id@assam.dankook.ac.kr

Some notices:
-. The server has a public domain name (with some basic security settings). Please treat it carefully. 
-. Please don't break into our system for any bad purposes.
-. Please don't forget your password. 3 consecutive password fails --> blocks your IP address for some time (not like seconds, but like hours)
-. If you forgot the password, please tell me so that I can unlock the IP address.
-. Please don't use a too simple password. There are really many attack attempts, and your account can be abused as a breach of the DKU IT infrastructure.

**Comment by min-guk** [comment]
Example.
0.    minguk.choi    minguk17

**Comment by gillyongs** [comment]
1. hansu.kim hansu27
감사합니다!

**Comment by sss654654** [comment]
2. subin.hong subin21

**Comment by cho-ja-young** [comment]
3. jayoung.cho jayoung26

감사합니다!

**Comment by seoyoung927** [comment]
4. seoyoung.cho seoyoung27
감사합니다!

**Comment by Cho-SangHyun** [comment]
5. sanghyun.cho sanghyun17

**Comment by seo-0** [comment]
6. seoyoung.park seoyoung20

**Comment by seehwan** [comment]
Initial access password is open in the seminar session; 
If you want to change it, please let me know. :)
You will be asked a new password in the next login.

1) ssh your_id@assam.dankook.ac.kr
--> enter password of assam (not visible)
2) --> enter solid password (not visible)

**Comment by isu-kim** [comment]
6. isu.kim isukim16

**Comment by SayOny** [comment]
7. seyeon.park seyeon22

기한이 지났지만 혹시 저도 된다면,, 참여시켜주시면 감사하겠습니다.

**Comment by min-guk** [comment]
오늘 교수님께서 기한이 지나도 괜찮다고 말씀하셨으니, 필요하신 학생들은 신청해주시면 감사하겠습니다.

**Comment by aarom416** [comment]
8. sangwoo kang, sangwoo41

**Comment by min-guk** [comment]
If you have any questions about server, please contact Taegyu Cho who works in professor Seehwan Yoo's laboratory.

Taegyu Cho, wh2446@dankook.ac.kr

**Comment by seehwan** [comment]
[solid_containers_cluster.pdf](https://github.com/DKU-StarLab/leveldb-study/files/9099159/solid_containers_cluster.pdf)

FYI. 
위에 계정 신청한 학생들-
오늘 밤에 비밀번호 설정을 다시 하겠습니다~
내일 다시 로그인 하면 새로운 비밀번호를 물어볼 겁니다. 
그 때 자기가 쓰는 비밀번호로 변경해서 사용하세요~

**Comment by seehwan** [comment]
News!

solid cloud server 설정이 거의 완료되어 공지합니다. 위에 요청한 account 생성이 완료되었으니 ssh로 연결확인 해 보기 바랍니다.
ssh your_id@assam.dankook.ac.kr

**Comment by ha-seungwon** [comment]
9. seungwon ha , seungwon24
늦게 말씀드려서 죄송합니다.

**Comment by seo-0** [comment]
10. seoyoung park, seoyoung99
